/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectofinalb;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Alejandro Junkai
 */
public class VentanaProyecto extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaProyecto
     */
    public VentanaProyecto() {
        initComponents();
        setVisible(true);
        setTitle("Proyecto");
        
        MetodosGenerales mg = new MetodosGenerales();
        jTextField1.addKeyListener(mg.soloLetrasYEspacios);
        jTextField2.addKeyListener(mg.soloNumeros);
        jTextField3.addKeyListener(mg.soloLetrasYEspacios);
        jTextField4.addKeyListener(mg.soloNumeros);
        
        jTextField1.addKeyListener(listener);
        jTextField2.addKeyListener(listener);
        jTextField3.addKeyListener(listener);
        jTextField4.addKeyListener(listener);
        
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
             if(!jComboBox1.getSelectedItem().toString().equals("Agregar") && !jComboBox1.getSelectedItem().toString().equals("Consultar")){
                if(!jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString().equals(""))
                jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                if(!jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString().equals(""))
                jTextField2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                if(!jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().equals(""))
                jTextField3.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
               if(!jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString().equals(""))
                jTextField4.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
                if(jComboBox1.getSelectedItem().toString().equals("Editar") || jComboBox1.getSelectedItem().toString().equals("Eliminar")){
                    jTextField2.setEditable(false);
                }
             }
        }
        });
        
        actualizarTabla("nombreproyecto is not null");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(102, 0, 51));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar", "Editar", "Consultar", "Eliminar" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Número del Proyecto:");
        jLabel1.setMaximumSize(new java.awt.Dimension(180, 32));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Agregar Proyecto");
        jLabel2.setMaximumSize(new java.awt.Dimension(180, 32));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre del Proyecto:");
        jLabel3.setMaximumSize(new java.awt.Dimension(180, 32));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("No. Dpto. Proyecto:");
        jLabel4.setMaximumSize(new java.awt.Dimension(180, 32));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ubicación del Proyecto:");
        jLabel5.setMaximumSize(new java.awt.Dimension(180, 32));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Proyecto", "Número Proyecto", "Ubicación Proyecto", "Departamento"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("X");
        jButton4.setPreferredSize(new java.awt.Dimension(38, 38));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Limpiar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(320, 320, 320))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     KeyListener listener = new KeyListener(){
        @Override
        public void keyReleased(KeyEvent event) {
            if(!jComboBox1.getSelectedItem().toString().equals("Agregar")){
                actualizarTabla(generarConsultaCampos());
            }
        }
        @Override
        public void keyTyped(KeyEvent e) {
            
        }
        @Override
        public void keyPressed(KeyEvent e) {
         
        }
    };
    
    public String generarConsultaCampos(){
        String consulta = "";
        if(!jTextField1.getText().equals(""))  
            consulta = consulta + "nombreproyecto like '%"+jTextField1.getText()+"%'";
        if(!jTextField2.getText().equals("")){
                    if(!consulta.equals(""))
                        consulta = consulta + " AND ";
                    consulta = consulta + "CAST(numproyecto as text) like '%"+jTextField2.getText()+"%'";
                }
        if(!jTextField3.getText().equals("")){
                    if(!consulta.equals(""))
                        consulta = consulta + " AND ";
                    consulta = consulta + "ubicacionproyecto like '%"+jTextField3.getText()+"%'";
                }
        if(!jTextField4.getText().equals("")){
                    if(!consulta.equals(""))
                        consulta = consulta + " AND ";
                    consulta = consulta + "CAST(numdptoproyecto as text) like '%"+jTextField4.getText()+"%'";
                }
        if(consulta.equals(""))
            consulta = "nombreproyecto is not null";
        return consulta;
    }
     
    public void limpiar(){
        Date fechaD = new Date();
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField2.setEditable(true);
        actualizarTabla("nombreproyecto is not null");
    }
    
    public void limpiarTabla(){
        for(int i=0; i<99; i++){
            for(int j=0; j<4; j++){
                jTable1.setValueAt("", i, j);
            }
        }
    }
    
    public void actualizarTabla(String parametro){
        ConexionBD cbd = ConexionBD.getConexionBD();
        limpiarTabla();
        String[][] tabla = cbd.obtenerRegistrosDepartamentos("vista_proyecto", parametro);
        for(int i=0; i<tabla.length; i++){
            for(int j=0; j<4; j++){
                jTable1.setValueAt(tabla[i][j], i, j);
            }
        }
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        ConexionBD cbd = ConexionBD.getConexionBD();
        switch(jComboBox1.getSelectedItem().toString()){
            case "Agregar":
            jLabel2.setText("Agregar Proyecto");
            jButton5.setVisible(true);
            jButton5.setText("Agregar");
            limpiar();
            break;
            case "Editar":
            jLabel2.setText("Editar Proyecto");
            jButton5.setVisible(true);
            jButton5.setText("Editar");
            limpiar();
            break;
            case "Consultar":
            jLabel2.setText("Consultar Proyecto");
            jButton5.setVisible(false);
            limpiar();
            break;
            case "Eliminar":
            jLabel2.setText("Eliminar Proyecto");
            jButton5.setVisible(true);
            jButton5.setText("Eliminar");
            limpiar();
            break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ConexionBD cbd = ConexionBD.getConexionBD();
        switch(jComboBox1.getSelectedItem().toString()){
            case "Agregar":
                if((jTextField1.getText().length()<4 || jTextField1.getText().length()>20) || jTextField2.getText().length()==0 || jTextField4.getText().length()==0 || (jTextField3.getText().length()<3 || jTextField3.getText().length()>20)){
                    JOptionPane.showMessageDialog(null,"La longitud de alguno de los campos de texto no es válida.\nIntentelo nuevamente...");
                }else{
                    if(cbd.verificarSiExiste("Proyecto", "numproyecto="+jTextField2.getText())){
                        JOptionPane.showMessageDialog(null,"Ya existe un Proyecto con el número ingresado.\nIntentelo nuevamente...");
                    }else{
                        if(cbd.verificarSiExiste("Departamento", "numerodpt="+jTextField4.getText())){
                        String insercion = "Proyecto(nombreproyecto, numproyecto, ubicacionproyecto, numdptoproyecto) values('"+jTextField1.getText()+"', "+jTextField2.getText()+", '"+jTextField3.getText()+"', "+jTextField4.getText()+")";
                        cbd.agregarRegistro(insercion);
                        JOptionPane.showMessageDialog(null,"Se ha agregado el proyecto correctamente.");
                        limpiar();
                        actualizarTabla("nombreproyecto is not null");
                        }else{
                            JOptionPane.showMessageDialog(null,"No existe un departamento con el número ingresado.");
                        }
                    }
                }
            break;
            case "Editar":
                if((jTextField1.getText().length()<4 || jTextField1.getText().length()>20) || jTextField2.getText().length()==0 || jTextField4.getText().length()==0 || (jTextField3.getText().length()<3 || jTextField3.getText().length()>20)){
                    JOptionPane.showMessageDialog(null,"La longitud de alguno de los campos de texto no es válida.\nIntentelo nuevamente...");
                }else{
                    if(cbd.verificarSiExiste("Departamento", "numerodpt="+jTextField4.getText())){
                        String datos="", donde="";
                        datos="nombreproyecto='"+jTextField1.getText()+"', ubicacionproyecto='"+jTextField3.getText()+"', numdptoproyecto="+jTextField4.getText();
                        donde = "numproyecto="+jTextField2.getText();
                        cbd.editarRegistro("Proyecto", datos, donde);
                        JOptionPane.showMessageDialog(null,"Se ha editado el registro correctamente.");
                        limpiar();
                        actualizarTabla("nombreproyecto is not null");
                    }else{
                            JOptionPane.showMessageDialog(null,"No existe un departamento con el número ingresado.");
                        }
                }
            case "Eliminar":
            if(jTextField2.getText().length()==0){
                JOptionPane.showMessageDialog(null,"Seleccione el registro que desea eliminar.");
            }else{
                if(cbd.verificarSiExiste("Proyecto", "numproyecto="+jTextField2.getText())){
                    cbd.eliminarRegistro("Proyecto", "numproyecto="+jTextField2.getText());
                    JOptionPane.showMessageDialog(null,"Se ha eliminado el registro correctamente.");
                    limpiar();
                    actualizarTabla("nombreproyecto is not null");
                }else JOptionPane.showMessageDialog(null,"No existe un registro con el número solicitado.");
            }
            break;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
